name: Deploy to EC2 and ECS
on:
  push:
    branches: [ main ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment: EC2
    steps:
      - name: Deploy to EC2
        id: ec2
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-rc
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-2
          app_port: 8000

          stack_destroy: false

          aws_resource_identifier: deno-ec2

  ECS-Deploy:
    runs-on: ubuntu-latest
    environment: ECS
    steps:
    - name: Create an ECS-Fargate deploy
      id: ecs
      uses: bitovi/github-actions-deploy-ecs@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
        aws_default_region: us-east-2

        aws_ecs_enable: true
        aws_ecs_app_image: bitovi/deno-demo:latest

        aws_ecs_task_cpu: 2048
        aws_ecs_task_mem: 6144

        aws_ecs_container_mem: 6144
        aws_ecs_container_cpu: 2048
        
        aws_ecs_cloudwatch_enable: true
        aws_ecs_cloudwatch_retention_days: 7

        aws_ecs_container_port: 8000
        aws_ecs_lb_port: 8000

        tf_stack_destroy: false

        aws_resource_identifier: deno-ecs