name: Deploy to EC2 and ECS
on:
  push:
    branches: [ main ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment: EC2
    steps:
      - name: Deploy to EC2
        id: ec2
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-rc
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-2
          app_port: 8000

          stack_destroy: true

          aws_resource_identifier: deno-ec2
