name: Deploy to EC2 and ECS
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment: 
      name: EC2
      url: ${{ steps.ec2.outputs.vm_url }}
    steps:
      - name: Deploy to EC2
        id: ec2
        uses: bitovi/github-actions-deploy-docker-to-ec2@commons-rc
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          app_port: 8000

          # stack_destroy: true
          tf_state_bucket_destroy: true

          aws_resource_identifier: deno-demo-ec2
          aws_r53_enable: true
          #aws_r53_domain_name: bitovi-sandbox.com
          domain_name: bitovi-sandbox.com
          #aws_r53_sub_domain_name: deno-ec2
          sub_domain: deno-ec2
          #aws_r53_enable_cert: true
          enable_cert: true

  ECS-Deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ECS
      url: ${{ steps.ecs.outputs.ecs_dns_record }}
    steps:
      - name: Deploy to ECS
        id: ecs
        #uses: bitovi/github-actions-deploy-ecs@main
        uses: bitovi/github-actions-deploy-ecs@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          aws_ecs_enable: true
          aws_ecs_app_image: bitovi/deno-demo:latest

          aws_ecs_task_cpu: 2048
          aws_ecs_task_mem: 4096

          aws_ecs_container_cpu: 2048
          aws_ecs_container_mem: 4096
          
          aws_ecs_cloudwatch_enable: true
          aws_ecs_cloudwatch_retention_days: 7

          aws_ecs_container_port: 8000
          aws_ecs_lb_port: 8000
          aws_ecs_lb_redirect_enable: true
          aws_ecs_assign_public_ip: true
          # tf_stack_destroy: true
          tf_state_bucket_destroy: true

          aws_resource_identifier: deno-demo-ecs
          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: deno-ecs
          aws_r53_enable_cert: true

          env_repo: repo_env