name: Deploy to ECS
on:
  push:
    branches: [  ]

jobs:
  ECS-Deploy:
    runs-on: ubuntu-latest
    environment: ECS
    steps:
      - name: Create an ECS-Fargate deploy
        id: ecs
        #uses: bitovi/github-actions-deploy-ecs@main
        uses: bitovi/github-actions-deploy-ecs@commons-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-2

          aws_ecs_enable: true
          aws_ecs_app_image: bitovi/deno-demo:latest

          aws_ecs_task_cpu: 2048
          aws_ecs_task_mem: 4096

          #aws_ecs_container_mem: 6144
          #aws_ecs_container_cpu: 2048
          
          aws_ecs_cloudwatch_enable: true
          aws_ecs_cloudwatch_retention_days: 7

          aws_ecs_container_port: 8000
          aws_ecs_lb_port: 8000
          aws_ecs_lb_redirect_enable: true
          #tf_stack_destroy: false

          aws_resource_identifier: deno-ecs

          aws_r53_enable: true
          aws_r53_domain_name: bitovi-sandbox.com
          aws_r53_sub_domain_name: ecs-final-testing
          aws_r53_enable_cert: true
